# Generated by Django 5.1.6 on 2025-03-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('imagem', models.URLField()),
            ],
        ),
    ]
